#!/usr/bin/env python3
"""Build a self-contained macOS .app for the cooking app, from any OS.

Unlike the Windows launcher -- which points at server.py where it already lives
on the same machine -- the Mac is a *different* machine, so the payload travels
with the bundle: server.py, src/, recipes/, recipe_images/ and conversions.json
are copied into Contents/Resources/app/. Recipes on the Mac are therefore a
copy; this repo stays the source of truth on this machine.

No cross-compilation and no runtime is staged: the launcher is a shell script
that finds the Mac's own python3 (stdlib only, as everywhere else in this app).

    python3 scripts/make_macos_bundle.py [--out build/macos] [--no-zip]
"""
from __future__ import annotations

import argparse
import shutil
import stat
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from appicon import build_icns  # noqa: E402  (after sys.path fixup)

APP_NAME = "Cooking App"
BUNDLE_ID = "local.cooking-app"
VERSION = "1.0"
PORT = 36637
EXECUTABLE = "cooking-app"

REPO = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO / "build" / "macos"

# Everything the server needs to run standalone. dist/ is deliberately absent:
# server.py serves src/ when src/recipes.html exists, which it always does here.
PAYLOAD = ("server.py", "conversions.json", "src", "recipes", "recipe_images")
SKIP = {"__pycache__", ".DS_Store", ".git"}


# --- Launcher -----------------------------------------------------------------
#
# Finder gives a .app a minimal PATH (/usr/bin:/bin:/usr/sbin:/sbin), so Homebrew
# pythons have to be probed by absolute path. /usr/bin/python3 is tried *last*:
# on a Mac without the Command Line Tools it is a stub that pops the "install
# developer tools" dialog when executed, which we would rather not trigger while
# a perfectly good Homebrew python sits one line above.

LAUNCHER = """#!/bin/sh
# Generated by scripts/make_macos_bundle.py -- do not edit by hand.
# Finds a python3 and hands it server.py from inside this bundle.
set -u

APP="$(cd "$(dirname "$0")/../Resources/app" && pwd)"

# Finder discards stdout/stderr; keep them next to the recipes like the Windows
# launcher does. A quarantined bundle can be read-only -- don't die over the log.
LOG="$APP/cooking-app.log"
: >>"$LOG" 2>/dev/null || LOG=/dev/null

for py in \\
    "$(command -v python3 2>/dev/null)" \\
    /opt/homebrew/bin/python3 \\
    /usr/local/bin/python3 \\
    /usr/bin/python3
do
    [ -n "$py" ] && [ -x "$py" ] || continue
    "$py" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)' \\
        >/dev/null 2>&1 || continue
    exec "$py" "$APP/server.py" >>"$LOG" 2>&1
done

MSG="{name} needs Python 3, and none was found.\\n\\nInstall Apple's with:    \
xcode-select --install\\nor get one from python.org, then open {name} again."
osascript -e "display dialog \\"$MSG\\" with title \\"{name}\\" buttons {{\\"OK\\"}} \
default button \\"OK\\" with icon caution" >/dev/null 2>&1
exit 1
"""

INFO_PLIST = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>              <string>{name}</string>
    <key>CFBundleDisplayName</key>       <string>{name}</string>
    <key>CFBundleIdentifier</key>        <string>{bundle_id}</string>
    <key>CFBundleExecutable</key>        <string>{executable}</string>
    <key>CFBundleIconFile</key>          <string>cooking</string>
    <key>CFBundlePackageType</key>       <string>APPL</string>
    <key>CFBundleSignature</key>         <string>????</string>
    <key>CFBundleInfoDictionaryVersion</key> <string>6.0</string>
    <key>CFBundleShortVersionString</key><string>{version}</string>
    <key>CFBundleVersion</key>           <string>{version}</string>
    <key>LSMinimumSystemVersion</key>    <string>10.13</string>
    <key>NSHighResolutionCapable</key>   <true/>
</dict>
</plist>
"""

READ_ME = """{name} for macOS
{rule}

1. Drag "{name}.app" to /Applications (or anywhere outside Downloads).

2. First launch only -- the app is unsigned, so macOS quarantines it:
       right-click the app -> Open -> Open
   or, from Terminal:
       xattr -dr com.apple.quarantine "/Applications/{name}.app"

   Do this before using it. Left quarantined, macOS may run the app from a
   read-only shadow copy, and recipes you add would silently disappear.

3. It opens http://localhost:{port}/ in your browser.
   Stop it with the Quit button in the app header -- there is no console.

Requires Python 3 (any 3.8+). If the Mac has none, the app says so on launch;
"xcode-select --install" is the quickest fix.

Your recipes live INSIDE the app bundle:
    right-click the app -> Show Package Contents
    -> Contents/Resources/app/recipes/        (one .md per recipe)
    -> Contents/Resources/app/recipe_images/
Back that folder up; a newer bundle replaces the app and everything in it.

Logs: Contents/Resources/app/cooking-app.log
"""


def _copy_payload(dest: Path) -> int:
    """Copy the runtime payload into dest. Returns the number of files."""
    dest.mkdir(parents=True, exist_ok=True)
    count = 0

    def ignore(_dir, names):
        return [n for n in names if n in SKIP or n.endswith(".pyc")]

    for name in PAYLOAD:
        src = REPO / name
        if not src.exists():
            raise SystemExit(f"missing from the repo: {src}")
        if src.is_dir():
            shutil.copytree(src, dest / name, ignore=ignore)
            count += sum(1 for p in (dest / name).rglob("*") if p.is_file())
        else:
            shutil.copy2(src, dest / name)
            count += 1
    return count


def build_app(out_dir: Path) -> Path:
    app = out_dir / f"{APP_NAME}.app"
    if app.exists():
        shutil.rmtree(app)

    contents = app / "Contents"
    macos, resources = contents / "MacOS", contents / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    (contents / "PkgInfo").write_text("APPL????", encoding="utf-8")
    (contents / "Info.plist").write_text(
        INFO_PLIST.format(
            name=APP_NAME, bundle_id=BUNDLE_ID, executable=EXECUTABLE, version=VERSION
        ),
        encoding="utf-8",
    )

    launcher = macos / EXECUTABLE
    launcher.write_text(LAUNCHER.format(name=APP_NAME), encoding="utf-8")
    launcher.chmod(0o755)

    icns = resources / "cooking.icns"
    icns.write_bytes(build_icns())
    print(f"  icon:    cooking.icns ({icns.stat().st_size // 1024} KB)")

    files = _copy_payload(resources / "app")
    print(f"  payload: {files} files ({', '.join(PAYLOAD)})")
    return app


def make_zip(out_dir: Path, app: Path, extra: list[Path]) -> Path:
    """Zip the app for transfer, preserving the launcher's executable bit.

    shutil.make_archive would drop it -- the file modes have to be written into
    the entries by hand, with a UNIX creator, or the Mac gets an app it cannot
    launch.
    """
    zip_path = out_dir / "cooking-app-macos.zip"
    top = f"{APP_NAME} for macOS"
    items: list[tuple[Path, str]] = [(p, f"{top}/{p.name}") for p in extra]
    items += [
        (p, f"{top}/{app.name}/{p.relative_to(app).as_posix()}")
        for p in sorted(app.rglob("*"))
        if p.is_file()
    ]

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path, arcname in items:
            info = zipfile.ZipInfo(arcname, date_time=(2026, 1, 1, 0, 0, 0))
            info.create_system = 3  # UNIX, so external_attr is read as st_mode
            mode = path.stat().st_mode
            if mode & stat.S_IXUSR:
                info.external_attr = 0o755 << 16
            else:
                info.external_attr = 0o644 << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, path.read_bytes())
    return zip_path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(DEFAULT_OUT),
                    help=f"output folder (default: {DEFAULT_OUT})")
    ap.add_argument("--no-zip", action="store_true",
                    help="leave the .app loose, skip the transfer zip")
    args = ap.parse_args()

    out_dir = Path(args.out).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"app:    {APP_NAME}.app")
    print(f"out:    {out_dir}")

    app = build_app(out_dir)

    readme = out_dir / "READ-ME-FIRST.txt"
    readme.write_text(
        READ_ME.format(name=APP_NAME, rule="=" * len(f"{APP_NAME} for macOS"), port=PORT),
        encoding="utf-8",
    )

    if not args.no_zip:
        zip_path = make_zip(out_dir, app, [readme])
        print(f"  zip:     {zip_path.name} ({zip_path.stat().st_size // 1024} KB)")

    print(
        f"\ndone. Copy {'the zip' if not args.no_zip else f'{APP_NAME}.app'} to the Mac"
        f" -- then read READ-ME-FIRST.txt (unsigned app: it needs one right-click"
        f" -> Open, or xattr -dr com.apple.quarantine)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
